# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter Name', max_length=50)),
                ('email', models.TextField(blank=True, help_text='Enter Email', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Enter Phone', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Enter Address', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
